# Generated by Django 6.0.7 on 2026-09-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Job seeker'), ('employer', 'Recruiter')], default='candidate', max_length=20),
        ),
    ]
