# Generated by Django 6.1.1 on 2026-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
